services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exemplo
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80